version: '3.9'

services:
  ner-api:
    build:
      context: ./ner-api
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - ./ner-api:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 5000