FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8

RUN apt-get -y update && apt-get -y install \
    python3 \
    python3-setuptools \
    python3-pip \
    python3-wheel \
    python3-cffi \
    automake \
    git \
    git-lfs \
    autoconf \
    && apt-get clean \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /ner_api
RUN pip install --upgrade pip

COPY requirements_dev.txt /app/requirements_dev.txt
RUN pip install --no-cache-dir -r /app/requirements_dev.txt

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

RUN rm -rf /root/.cache/pip